###
GET http://localhost:3000/api/empleados

###
POST http://localhost:3000/api/empleados
Content-Type: application/application/json
{
    "nombre":"Stephany Contreras",
    "cargo":"gerente",
    "departamento":"TI",
    "sueldo":"3000"
}